# Generated by Django 3.2.11 on 2022-01-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
